In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [9]:
b=np.array([(1,2,3,4),(5,6,7,8)])

In [10]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
trans=np.transpose(b)

In [12]:
print(trans)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
trans.ravel()

array([1, 5, 2, 6, 3, 7, 4, 8])

In [14]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
z=np.zeros((9,5))

In [16]:
z


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
a.resize(2,4
        )

In [18]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.append(trans,z)

array([1., 5., 2., 6., 3., 7., 4., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [20]:
np.append(trans,a)

array([1, 5, 2, 6, 3, 7, 4, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.append(a,z)

array([1., 2., 3., 4., 5., 6., 7., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [22]:
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.insert(a,2,5)

array([1, 2, 5, 3, 4, 5, 6, 7, 8])

In [24]:
trans


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
c=np.insert(z,9,10)

In [32]:
c


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [34]:
np.delete(a,[1])

array([1, 3, 4, 5, 6, 7, 8])

In [35]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
e=np.delete(a,[1])

In [37]:
e

array([1, 3, 4, 5, 6, 7, 8])

In [38]:
txt=np.array([(1,2),(5,8)])

In [39]:
txt

array([[1, 2],
       [5, 8]])

In [40]:
np.concatenate((txt,txt),axis=None)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [41]:
np.hstack((txt,txt))

array([[1, 2, 1, 2],
       [5, 8, 5, 8]])

In [42]:
np.vstack((txt,txt))

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [50]:
np.vsplit(txt,2)

[array([[1, 2]]), array([[5, 8]])]